# .goreleaser.yml
project_name: gitprofile

builds:
  - id: gitprofile
    main: ./
    binary: gitprofile
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: gitprofile
    builds:
      - gitprofile

# This configuration will publish the formula to a 'Formula' directory
# in this same repository.
brews:
  - name: gitprofile
    # This makes GoReleaser push to the main repo.
    repository:
      owner: henryyr
      name: gitprofile
      # We use a token to allow pushing to the repo.
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/henryyr/gitprofile"
    description: "A CLI to manage multiple git profiles"
    license: "Apache-2.0"

# This configuration will publish the manifest to a 'scoop' directory
# in this same repository.
scoop:
  name: gitprofile
  # This makes GoReleaser push to the main repo.
  repository:
    owner: henryyr
    name: gitprofile
    token: "{{ .Env.GITHUB_TOKEN }}"
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com
  homepage: "https://github.com/henryyr/gitprofile"
  description: "A CLI to manage multiple git profiles."
  license: "Apache-2.0"

# Linux packages are unaffected and will be attached to the release.
nfpms:
  - id: gitprofile-nfpms
    package_name: gitprofile
    formats:
      - deb
      - rpm
    vendor: henryyr
    homepage: "https://github.com/henryyr/gitprofile"
    maintainer: "henryyr <henry.360420@gmail.com>"
    description: "A CLI to manage multiple git profiles."
    license: "Apache-2.0"
    bindir: /usr/local/bin
